#Query the AWS-maintained AMIs via SSM parameters
#aws ssm get-parameters-by-path --path /aws/service/ami-windows-latest | jq ".Parameters[].Name" | grep "English" | grep "\-2019"
#or

#choose the appropriate AMI path and include in CFN parameters
AWSTemplateFormatVersion: 2010-09-09

Description: Launch EC2 instance through launch template

Parameters:
   UbuntuLatestAMI:
     Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
     Default: /aws/service/canonical/ubuntu/server/18.04/stable/current/amd64/hvm/ebs-gp2/ami-id
Resources:
   MyLaunchTemplateDbb: 
      Type: AWS::EC2::LaunchTemplate
      Properties: 
        LaunchTemplateData: 
          InstanceType: t2.micro
          KeyName: dbb
          SecurityGroupIds: 
          - sg-04451ea6d4982b110
          - !GetAtt MySecurityGroupdbb.GroupId
          IamInstanceProfile:
            Name: !Ref MyCloudWatchInstanceProfile
          TagSpecifications: 
          - ResourceType: instance
            Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "5.2"
            - Key: stelligent-u-lab
              Value: "5.2.1"
          UserData:
            Fn::Base64: 
              !Sub |
                #!/bin/bash
                sudo yum update -y 
                sudo yum -y install amazon-cloudwatch-agent
        LaunchTemplateName: Stelligent-u-dbb
   MyEc2Ubuntu:
     Type: AWS::EC2::Instance
     Properties:
        ImageId: !Ref UbuntuLatestAMI  
        LaunchTemplate:
          LaunchTemplateId: !Ref MyLaunchTemplateDbb
          Version: !GetAtt MyLaunchTemplateDbb.LatestVersionNumber
   MyElacticIPdbb:
      Type: AWS::EC2::EIP
      Properties: 
        Domain: vpc
        InstanceId: !Ref MyEc2Ubuntu
        Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "5.2"
            - Key: stelligent-u-lab
              Value: "5.2.1"
   MySecurityGroupdbb:
      Type: AWS::EC2::SecurityGroup
      Properties: 
        GroupDescription: Allow ICMP trafic
        SecurityGroupIngress: 
        - Description: Allow all traffic from ICMP from everywhere
          CidrIp: 0.0.0.0/0
          IpProtocol: icmp
          FromPort: -1
          ToPort: -1
        - Description: Allow SSH trafic from everywhere
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        Tags: 
        - Key: user
          Value: desire.bahbioh.labs
        - Key: stelligent-u-lesson
          Value: "5.3"
        - Key: stelligent-u-lab
          Value: "5.3.2"
   CloudwatchRole:
      Type: AWS::IAM::Role
      Properties: 
        AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement: 
            - Effect: "Allow"
              Principal: 
                Service: 
                - "ec2.amazonaws.com"
              Action: 
              - "sts:AssumeRole"
        Description: Role to access cloudwatch metrics
        ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy
        RoleName: cwagent-role
        Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "5.3"
            - Key: stelligent-u-lab
              Value: "5.3.2"
   MyCloudWatchInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties: 
        InstanceProfileName: cwagent-instance-profile
        Roles: 
        - !Ref CloudwatchRole

Outputs:
  UbuntuElasticIP:
     Description: Elastic Ip of ubuntu instance
     Value: !Ref MyElacticIPdbb
  UbuntuInstanceId:
     Description: Ubuntu instance Id
     Value: !Ref MyEc2Ubuntu
      