AWSTemplateFormatVersion: 2010-09-09
Description: Private Ec2 instance in us-west-2

Resources: 
    PeerPrivateEc2:
        Type: AWS::EC2::Instance
        Properties: 
          AvailabilityZone: "us-west-2a"
          SubnetId: subnet-04bcd5ec397357864
          ImageId: ami-0a36eb8fadc976275
          InstanceType: t2.micro
          KeyName: dezKey
          Tenancy: default
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.2"
            - Key: stelligent-u-lab
              Value: "4.2.2"
          SecurityGroupIds:
          - !Ref DesiSecurityGroups
    DesiSecurityGroups:
        Type: AWS::EC2::SecurityGroup
        Properties: 
          GroupDescription: Allow ICMP and ssh
          GroupName: sshpingpeer
          SecurityGroupIngress: 
          - IpProtocol: icmp
            FromPort: -1
            ToPort: -1
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.2"
            - Key: stelligent-u-lab
              Value: "4.2.2"
          VpcId: vpc-0b03386f014ba3bfe

Outputs:
  PrivateInstancePrivateIP:
    Description: private instance ip address
    Value: !GetAtt PeerPrivateEc2.PrivateIp