AWSTemplateFormatVersion: 2010-09-09

Description: Private EC2 in us-west-1

Resources:
    DesiPrivateEc2:
        Type: AWS::EC2::Instance
        Properties: 
          AvailabilityZone: "us-west-1a"
          SubnetId: subnet-08038c01c7e2b4614
          ImageId: ami-03130878b60947df3 
          InstanceType: t2.micro 
          KeyName: dezKey
          Tenancy: default
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"
          SecurityGroupIds:
          - !Ref DesiSecurityGroups
    DesiSecurityGroups:
        Type: AWS::EC2::SecurityGroup
        Properties: 
          GroupDescription: Allow ICMP and ssh
          GroupName: sshping
          SecurityGroupIngress: 
          - IpProtocol: icmp
            FromPort: -1
            ToPort: -1
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"
          VpcId: vpc-0966d2e6f14eb801e
Outputs:
  PrivateInstancePrivateIP:
    Description: private instance ip address
    Value: !GetAtt DesiPrivateEc2.PrivateIp
