AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role with read-only access to all IAM resources

Resources: 
   IAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: iam-role
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal:
              Service: 
                - "iam.amazonaws.com"
            Action: "sts:AssumeRole"
   IAMReadOnlyPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: iam-read-only
        Description: Policy allowing read-only access on IAM resources
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: "iam:Get*"
            Resource: "*"
        Roles:
        - !Ref IAMRole

