AWSTemplateFormatVersion: 2010-09-09
Description: User assuming a Role
Resources:
   MyS3Bucket1:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: unrestricted.desirebb1
   MyS3Bucket2:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: unrestricted.desirebb2
   S3RestrictRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal: 
              AWS: arn:aws:iam::324320755747:user/desire.bahbioh.labs
            Action: "sts:AssumeRole"
        Policies:
          - PolicyDocument:
              Version: 2012-10-17
              Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: arn:aws:s3:::unrestricted.desirebb1
            PolicyName: s3full
          - PolicyDocument:
              Version: 2012-10-17
              Statement:
              - Effect: Allow
                Action: 
                - 's3:Get*'
                - 's3:List*'
                Resource: arn:aws:s3:::unrestricted.desirebb2
            PolicyName: s3read
        RoleName: iam-s3-restrict
Outputs:
  RoleArn:
     Description: Arn of s3fullaccess
     Value: !GetAtt S3RestrictRole.Arn