AWSTemplateFormatVersion: 2010-09-09

Description: launching test instance

Parameters:
    AMI:
      Type: AWS::EC2::Image::Id
    InstanceType:
      Type: String
    KeyPair:
      Type: AWS::EC2::KeyPair::KeyName
Resources:
    DesiEc2:
        Type: AWS::EC2::Instance
        Properties: 
          AvailabilityZone: "us-east-1a"
          SubnetId: subnet-051cac299ed6df556
          ImageId: !Ref AMI
          InstanceType: !Ref InstanceType
          KeyName: !Ref KeyPair
          Tenancy: default
          PrivateIpAddress: 10.16.0.5
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.4"

Outputs:
  InstanceId:
    Description: Ec2 instance ID
    Value: !Ref DesiEc2
  PrivateIP:
    Description: private ip address
    Value: !GetAtt DesiEc2.PrivateIp