#Query the AWS-maintained AMIs via SSM parameters
#aws ssm get-parameters-by-path --path /aws/service/ami-windows-latest | jq ".Parameters[].Name" | grep "English" | grep "\-2019"
#or

#choose the appropriate AMI path and include in CFN parameters
AWSTemplateFormatVersion: 2010-09-09

Description: Launch EC2 instance through launch template

Resources:
   MyEc2Ubuntu:
     Type: AWS::EC2::Instance           
     Properties:
        ImageId: ami-0e600b4c09bc346ed
        InstanceType: t2.micro
        KeyName: dbb
        SecurityGroupIds:
        - !Ref MySecurityGroupdbb
   MyElacticIPdbb:
      Type: AWS::EC2::EIP
      Properties: 
        Domain: vpc
        InstanceId: !Ref MyEc2Ubuntu
        Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "5.2"
            - Key: stelligent-u-lab
              Value: "5.2.1"
   MySecurityGroupdbb:
      Type: AWS::EC2::SecurityGroup
      Properties: 
        GroupDescription: Allow ICMP trafic
        SecurityGroupIngress: 
        - Description: Allow all traffic from ICMP from everywhere
          CidrIp: 0.0.0.0/0
          IpProtocol: icmp
          FromPort: -1
          ToPort: -1
        - Description: Allow SSH trafic from everywhere
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        Tags: 
        - Key: user
          Value: desire.bahbioh.labs
        - Key: stelligent-u-lesson
          Value: "5.3"
        - Key: stelligent-u-lab
          Value: "5.3.2"

Outputs:
  UbuntuElasticIP:
     Description: Elastic Ip of ubuntu instance
     Value: !Ref MyElacticIPdbb
  UbuntuInstanceId:
     Description: Ubuntu instance Id
     Value: !Ref MyEc2Ubuntu
      