AWSTemplateFormatVersion: 2010-09-09

Description: Cloudwatch logs lab 8.2
 
Resources: 
    MyLogGroup:
      Type: AWS::Logs::LogGroup
      Properties: 
        LogGroupName: dbb.8.2.1
        RetentionInDays: 60
    
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: stelligent-u-dbb-cwlogs 
  
    MyBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref MyBucket
        PolicyDocument:
          Statement:
          - Action: 
            - "s3:*"
            Effect: Allow  
            Resource: 
            - "arn:aws:s3:::stelligent-u-dbb-cwlogs/*"
            - "arn:aws:s3:::stelligent-u-dbb-cwlogs"
            Principal:
               Service: 
               - cloudtrail.amazonaws.com

    MyCloudWatchRole:
       Type: AWS::IAM::Role
       Properties: 
          AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Principal:
                Service:
                - cloudtrail.amazonaws.com
              Action:
              - 'sts:AssumeRole'
          ManagedPolicyArns: 
            - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
          RoleName: !Join ["",[!Ref AWS::Region, cw-role ]] 
          Tags: 
          - Key: user
            Value: desire.bahbioh.labs
          - Key: stelligent-u-lesson
            Value: "8.2"
          - Key: stelligent-u-lab
            Value: "8.2.1"
    
    MyCloudTrail:
        Type: AWS::CloudTrail::Trail
        Properties: 
          CloudWatchLogsLogGroupArn: !GetAtt MyLogGroup.Arn
          CloudWatchLogsRoleArn: !GetAtt MyCloudWatchRole.Arn 
          IsLogging: true
          S3BucketName: !Ref MyBucket
          Tags: 
          - Key: user
            Value: desire.bahbioh.labs
          - Key: stelligent-u-lesson
            Value: "8.2"
          - Key: stelligent-u-lab
            Value: "8.2.1"
