AWSTemplateFormatVersion: 2010-09-09

Description: EC2 instance launch template for ASG

Resources:
   MyLaunchTemplateDbb: 
      Type: AWS::EC2::LaunchTemplate
      Properties: 
        LaunchTemplateData: 
          ImageId: ami-007a4d852ac16f59e
          InstanceType: t2.micro
          KeyName: dbb
          TagSpecifications: 
          - ResourceType: instance
            Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "6.1"
            - Key: stelligent-u-lab
              Value: "6.1.5"
   MyAutoScalingGroupdbb:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties: 
          AvailabilityZones:
          - us-east-1a
          DesiredCapacity: "1"
          HealthCheckType: EC2
          LaunchTemplate:
            LaunchTemplateId: !Ref MyLaunchTemplateDbb
            Version: !GetAtt MyLaunchTemplateDbb.LatestVersionNumber
          MaxSize: "2"
          MinSize: "1"
          Tags: 
          - Key: user
            Value: desire.bahbioh.labs
            PropagateAtLaunch: true
          - Key: stelligent-u-lesson
            Value: "6.1"
            PropagateAtLaunch: true
          - Key: stelligent-u-lab
            Value: "6.1.5"
            PropagateAtLaunch: true
          VPCZoneIdentifier:
          - subnet-0ddf1015d31bb8469
        UpdatePolicy:
           AutoScalingReplacingUpdate:
              WillReplace: true