AWSTemplateFormatVersion: 2010-09-09
Description: Lamdba hello world function
Resources:
  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Description: Lambda execution role
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      RoleName:
        Fn::Join:
        - ''
        - - Ref: AWS::Region
          - mylambda-role
      Tags:
      - Key: user
        Value: desire.bahbioh.labs
      - Key: stelligent-u-lesson
        Value: '9.1'
      - Key: stelligent-u-lab
        Value: 9.1.1
  MyLambdaHelloFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: bucket-forlambda-dbb
        S3Key: d8287f79e70c7984b6c5d1f38a6f491e
      Handler: index.handler
      Description: Hello World function
      Role:
        Fn::GetAtt:
        - MyLambdaExecutionRole
        - Arn
      Runtime: nodejs12.x
      Tags:
      - Key: user
        Value: desire.bahbioh.labs
      - Key: stelligent-u-lesson
        Value: '9.1'
      - Key: stelligent-u-lab
        Value: 9.1.1
      TracingConfig:
        Mode: Active
  MyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - MyLambdaHelloFunction
        - Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyRestApi}/*/*
  MyRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: A test API
      Name: MyRestAPI
      EndpointConfiguration:
        Types:
        - REGIONAL
      Tags:
      - Key: user
        Value: desire.bahbioh.labs
      - Key: stelligent-u-lesson
        Value: '9.1'
      - Key: stelligent-u-lab
        Value: 9.1.1
  MyGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId:
        Ref: MyRestApi
      ResourceId:
        Fn::GetAtt:
        - MyRestApi
        - RootResourceId
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaHelloFunction.Arn}/invocations
  MyApiGatewayDeployment:
    DependsOn: MyGetMethod
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: MyRestApi
      Description: My deployment
      StageName: dummy
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      - AttributeName: Product_Name
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      - AttributeName: Product_Name
        KeyType: RANGE
      TableName: Product
      Tags:
      - Key: user
        Value: desire.bahbioh.labs
      - Key: stelligent-u-lesson
        Value: '9.2'
      - Key: stelligent-u-lab
        Value: 9.2.1
Outputs:
  RestApiID:
    Description: REST API id
    Value:
      Ref: MyRestApi
  RootResourceID:
    Description: Root resource id
    Value:
      Fn::GetAtt:
      - MyRestApi
      - RootResourceId
