AWSTemplateFormatVersion: 2010-09-09

Description: EC2 instance launch template for ASG

Resources:
   MyASGLaunchConfigdbb:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties: 
          AssociatePublicIpAddress: true
          ImageId: ami-007a4d852ac16f59e
          InstanceMonitoring: false
          InstanceType: t2.medium
          KeyName: dbb
   MyAutoScalingGroupdbb:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties: 
          AvailabilityZones:
          - us-east-1a
          DesiredCapacity: "1"
          HealthCheckType: EC2
          LaunchConfigurationName: !Ref MyASGLaunchConfigdbb
          MaxSize: "2"
          MinSize: "1"
          Tags: 
          - Key: user
            Value: desire.bahbioh.labs
            PropagateAtLaunch: true
          - Key: stelligent-u-lesson
            Value: "6.1"
            PropagateAtLaunch: true
          - Key: stelligent-u-lab
            Value: "6.1.2"
            PropagateAtLaunch: true
          VPCZoneIdentifier:
          - subnet-0ddf1015d31bb8469
        UpdatePolicy:
           AutoScalingReplacingUpdate:
              WillReplace: true