AWSTemplateFormatVersion: 2010-09-09

Description: "template that create an s3 bucket"
#https://aws.amazon.com/blogs/devops/passing-parameters-to-cloudformation-stacks-with-the-aws-cli-and-powershell/
Parameters:
   TheBucketName:
      Type: String
      Description: "name of the bucket"

Conditions:
   PreferedRegion:
      !Equals [!Ref AWS::Region, us-east-1]
   NotPreferedRegion:
      !Not [!Equals [!Ref AWS::Region, us-east-1]]

Resources: 
    MyPreferredS3Bucket:
       Type: "AWS::S3::Bucket"
       Condition: PreferedRegion
       Properties:
         #append acct_id to bucket name if within prefered region
         BucketName: !Join ["-",[!Ref "AWS::AccountId",!Ref TheBucketName]]

    MyOtherS3Bucket:
       Type: "AWS::S3::Bucket"
       Condition: NotPreferedRegion
       Properties:
         #append region name to bucket name if not in prefered region
         BucketName: !Join ["-",[!Ref "AWS::Region",!Ref TheBucketName]]