AWSTemplateFormatVersion: 2010-09-09
Description: custom peered vpc 

Parameters: 
     PeeredVpcCidrBlock:
        Description: Cidr block of peered vpc
        Type: String
     RequesterVpcCidrBlock:
        Description: Cidr block of the requester vpc
        Type: String
     PeeredVPCId:
        Description: id of peered VPC
        Type: String
     RequesterVPCId:
        Description: id of Requester VPC
        Type: String

Resources: 
#peer vpc
      PeeredVPC:
          Type: AWS::EC2::VPC
          Properties:
            CidrBlock: !Ref PeeredVpcCidrBlock
            InstanceTenancy: default
            Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.2"
            - Key: stelligent-u-lab
              Value: "4.2.1"
#subnet
      PrivateSubnet:
          Type: AWS::EC2::Subnet
          Properties: 
            AvailabilityZone: us-west-2a
            CidrBlock: 192.168.0.0/24
            Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.2"
            - Key: stelligent-u-lab
              Value: "4.2.1"
            VpcId: !Ref PeeredVPCId
#route table
      PeeredVPCRouteTable:
          Type: AWS::EC2::RouteTable
          Properties: 
            Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.2"
            - Key: stelligent-u-lab
              Value: "4.2.1"
            VpcId: !Ref PeeredVPC
#routes
      PeeredVPCRoute:
         Type: AWS::EC2::Route
         Properties: 
           RouteTableId: !Ref PeeredVPCRouteTable
           VpcPeeringConnectionId: pcx-02d9f70bcb8278617
           DestinationCidrBlock: !Ref RequesterVpcCidrBlock
#subnet-route-table association
      PrivateSubnetRtableAsssoc:
          Type: AWS::EC2::SubnetRouteTableAssociation
          Properties: 
            RouteTableId: !Ref PeeredVPCRouteTable
            SubnetId: !Ref PrivateSubnet
    
#Nacl 
      NaclForPeeredVPc:
          Type: AWS::EC2::NetworkAcl
          Properties: 
            Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.2"
            - Key: stelligent-u-lab
              Value: "4.2.1"
            VpcId: !Ref PeeredVPC
      # Nacl entries rules
      AllTrafficFromRequesterVPCInbound:
          Type: AWS::EC2::NetworkAclEntry
          Properties: 
            CidrBlock: !Ref RequesterVpcCidrBlock
            NetworkAclId: !Ref NaclForPeeredVPc
            Protocol: -1
            RuleAction: allow
            RuleNumber: 100
      AllTrafficToRequesterVPCOutbound:
          Type: AWS::EC2::NetworkAclEntry
          Properties: 
            CidrBlock: !Ref RequesterVpcCidrBlock
            Egress: true
            NetworkAclId: !Ref NaclForPeeredVPc
            Protocol: -1
            RuleAction: allow
            RuleNumber: 100
#Nacl subnet association
      NaclPrivateSubnetAssociation:
          Type: AWS::EC2::SubnetNetworkAclAssociation
          Properties: 
            NetworkAclId: !Ref NaclForPeeredVPc
            SubnetId: !Ref PrivateSubnet
Outputs:
  PeeredVPCid:
    Description: peered VPC id 
    Value: !Ref PeeredVPC
  RequesterVPCid:
    Description: id of Requester VPC 
    Value: !Ref RequesterVPCId
  SubnetID:
    Description: private subnet ID for peered VPC
    Value: !Ref PrivateSubnet