AWSTemplateFormatVersion: 2010-09-09
Description: custom vpc 

Parameters: 
      VpcAccepterCidrBlock:
        Description: Cidr block
        Type: String
        Default: 192.168.0.0/20

Resources: 
#vpc
      AccepterVPC:
          Type: AWS::EC2::VPC
          Properties:
            CidrBlock: !Ref VpcAccepterCidrBlock
            InstanceTenancy: default
            Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"

#private subnet
      DPrivateSubnet:
          Type: AWS::EC2::Subnet
          Properties:
            AvailabilityZone: "us-west-1a"
            VpcId: !Ref AccepterVPC
            CidrBlock: 192.168.0.0/24
            Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"

#route table
      AccepterRouteTable:
          Type: AWS::EC2::RouteTable
          Properties: 
            Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"
            VpcId: !Ref AccepterVPC
      
#subnet route table association(private subnet)
      DesiPrivateSbnRtTbAssoc:
          Type: AWS::EC2::SubnetRouteTableAssociation
          Properties: 
             RouteTableId: !Ref AccepterRouteTable
             SubnetId: !Ref DPrivateSubnet
#routes
      AccepterVpcRoute:
          Type: AWS::EC2::Route
          Properties: 
            RouteTableId: !Ref AccepterRouteTable
            VpcPeeringConnectionId: pcx-082ed02c8bc1aa075
            DestinationCidrBlock: 10.16.0.0/16
         
     
#NACl
      AccepterPrivateNacl:
          Type: AWS::EC2::NetworkAcl
          Properties: 
            Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"
            VpcId: !Ref AccepterVPC
   #nacl entries rules
      TrafficFromRequesterVpcInbound:
          Type: AWS::EC2::NetworkAclEntry
          Properties: 
            CidrBlock: 10.16.0.0/16
            NetworkAclId: !Ref AccepterPrivateNacl
            Protocol: -1
            RuleAction: allow
            RuleNumber: 100
      TrafficToRequesterVpcOutbound:
          Type: AWS::EC2::NetworkAclEntry
          Properties: 
            CidrBlock: 10.16.0.0/16
            NetworkAclId: !Ref AccepterPrivateNacl
            Egress: true
            Protocol: -1
            RuleAction: allow
            RuleNumber: 100
                
Outputs:
      VPCid:
        Description: the VPC id 
        Value: !Ref AccepterVPC
      PrivateSubnetid:
        Description: private subnet id
        Value: !Ref DPrivateSubnet