AWSTemplateFormatVersion: 2010-09-09
Description: User assuming a Role
Resources:
   S3role:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal: 
              AWS: arn:aws:iam::324320755747:user/desire.bahbioh.labs
            Action: "sts:AssumeRole"
        ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        RoleName: iam-ro-s3
   S3Bucket1:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: unrestricted.desirebahbioh1
   S3Bucket2:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: unrestricted.desirebahbioh2
Outputs:
  RoleArn:
     Description: Arn of s3fullaccess
     Value: !GetAtt S3role.Arn