AWSTemplateFormatVersion: 2010-09-09

Description: EC2 instance launch template for ASG

Resources:
   MyEc2Debian:
     Type: AWS::EC2::Instance           
     Properties:
        ImageId: ami-007a4d852ac16f59e
        InstanceType: t2.micro
        KeyName: dbb
        SecurityGroupIds:
        - !Ref MySecurityGroupdbb
   MyElacticIPdbb:
      Type: AWS::EC2::EIP
      Properties: 
        Domain: vpc
        InstanceId: !Ref MyEc2Debian
        Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "6.1"
            - Key: stelligent-u-lab
              Value: "6.1.1"
   MySecurityGroupdbb:
      Type: AWS::EC2::SecurityGroup
      Properties: 
        GroupDescription: Allow ICMP trafic
        SecurityGroupIngress: 
        - Description: Allow all traffic from ICMP from everywhere
          CidrIp: 0.0.0.0/0
          IpProtocol: icmp
          FromPort: -1
          ToPort: -1
        - Description: Allow SSH trafic from everywhere
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        Tags: 
        - Key: user
          Value: desire.bahbioh.labs
        - Key: stelligent-u-lesson
          Value: "6.1"
        - Key: stelligent-u-lab
          Value: "6.1.1"

Outputs:
  ElasticIP:
     Description: Elastic Ip of Debian instance
     Value: !Ref MyElacticIPdbb
  InstanceId:
     Description: Debian instance Id
     Value: !Ref MyEc2Debian