#when running this stack use the default value 
#(!GetAtt ImportedStackName.Default) of the newuser2.yaml file
AWSTemplateFormatVersion: 2010-09-09
Description: "create a new user and a policy that manages that user"

Parameters:
  NewUserName:
    Type: String
    Default: cfnuser

Resources:
   NewIamUser:
     Type: AWS::IAM::User
     Properties:
       UserName: !Ref NewUserName
       LoginProfile:
          Password: myP@ssword1!
       ManagedPolicyArns:
       - !Ref ReadAllS3Buckets
   
   ReadAllS3Buckets:
     Type: AWS::IAM::ManagedPolicy
     Properties:
       ManagedPolicyName: reads3bucket
       PolicyDocument: 
          Version: 2012-10-17
          Statement:
          - Sid: AllowListingReading
            Effect: Allow
            Action: 
            - s3:ListAllMyBuckets
            - s3:ListBucket
            - s3:GetObject
            Resource: "*"

Outputs:
  ManagedPolicyArn:
     Description: Managed policy Arn
     Value: !Ref ReadAllS3Buckets
     Export:
       Name: !Join [ "-", [ !Sub "${AWS::StackName}", ManagedPolicyARN ] ]