AWSTemplateFormatVersion: 2010-09-09
Description: "Create and assign an IAM policy to user"
Resources:  
   ReadAllS3Buckets:
     Type: AWS::IAM::ManagedPolicy
     Properties:
       ManagedPolicyName: reads3bucket
       PolicyDocument: 
          Version: 2012-10-17
          Statement:
          - Sid: AllowListingReading
            Effect: Allow
            Action: "s3:*"
            Resource: 
            - "arn:aws:s3:::stelligent-u-desire.bahbioh"
            - "arn:aws:s3:::stelligent-u-desire.bahbioh/*"
       Users:
        - "desire.bahbioh.labs"