#Query the AWS-maintained AMIs via SSM parameters
#aws ssm get-parameters-by-path --path /aws/service/ami-windows-latest | jq ".Parameters[].Name" | grep "English" | grep "\-2019"
#or

#choose the appropriate AMI path and include in CFN parameters
AWSTemplateFormatVersion: 2010-09-09

Description: Launch EC2 instance through launch template

Parameters:
   WindowLastestAMI:
     Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
     Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Core-Base
   UbuntuLatestAMI:
     Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
     Default: /aws/service/canonical/ubuntu/server/bionic/stable/current/amd6/hvm/ebs-gp2/ami-id
Resources:
   MyLaunchTemplateDbb: 
      Type: AWS::EC2::LaunchTemplate
      Properties: 
        LaunchTemplateData: 
          InstanceType: t2.micro
          KeyName: dezKey
          SecurityGroupIds: 
          - sg-04451ea6d4982b110
          TagSpecifications: 
          - ResourceType: instance
            Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "5.1.1"
        LaunchTemplateName: Stelligent-u-dbb
   MyEc2Windows:
     Type: AWS::EC2::Instance
     Properties:
        ImageId: !Ref WindowLastestAMI 
        LaunchTemplate:
          LaunchTemplateId: !Ref MyLaunchTemplateDbb
          Version: !GetAtt MyLaunchTemplateDbb.LatestVersionNumber
   MyEc2Ubuntu:
     Type: AWS::EC2::Instance
     Properties:
        ImageId: !Ref UbuntuLatestAMI  
        LaunchTemplate:
          LaunchTemplateId: !Ref MyLaunchTemplateDbb
          Version: !GetAtt MyLaunchTemplateDbb.LatestVersionNumber
