AWSTemplateFormatVersion: 2010-09-09
Description: "Create and assign an IAM policy to user"
Resources: 
   MyBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: stelligent-u-desire.bb 
  
   MyBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref MyBucket
        PolicyDocument:
          Statement:
          - Action: 
            - "s3:*"
            Effect: Allow  
            Resource: 
            - "arn:aws:s3:::stelligent-u-desire.bb/*"
            - "arn:aws:s3:::stelligent-u-desire.bb"
            Principal: "*"
            Condition:
                StringEquals:
                      aws:sourceVpce: VpcEndpointToS3
  
   AccessBuckets:
     Type: AWS::IAM::ManagedPolicy
     Properties:
       ManagedPolicyName: s3bucketAccess
       PolicyDocument: 
          Version: 2012-10-17
          Statement:
          - Sid: allowfullaccess
            Effect: Allow
            Action: "s3:*"
            Resource: 
            - "arn:aws:s3:::stelligent-u-desire.bb/*"
            - "arn:aws:s3:::stelligent-u-desire.bb"
       Users:
        - "desire.bahbioh.labs"