AWSTemplateFormatVersion: 2010-09-09
Description: "Create and assign an IAM policy to user"
Resources: 
   MyBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: stelligent-u-desire.bbb 
  
   MyBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref MyBucket
        PolicyDocument:
          Statement:
          - Action: 
            - "s3:*"
            Effect: Allow  
            Resource: 
            - "arn:aws:s3:::stelligent-u-desire.bbb/*"
            - "arn:aws:s3:::stelligent-u-desire.bbb"
            Principal: "*" 
            Condition:
                    StringEquals:
                        aws:sourceVpce: vpce-0b3407d9ecd5222d7
   AccessBuckets:
     Type: AWS::IAM::ManagedPolicy
     Properties:
       ManagedPolicyName: s3bucketAccess
       PolicyDocument: 
          Version: 2012-10-17
          Statement:
          - Sid: allowfullaccess
            Effect: Allow
            Action: "s3:*"
            Resource: 
            - "arn:aws:s3:::stelligent-u-desire.bbb/*"
            - "arn:aws:s3:::stelligent-u-desire.bbb"
       Users:
        - "desire.bahbioh.labs"