AWSTemplateFormatVersion: 2010-09-09
Description: custom vpc 

Parameters: 
      VpcAccepterCidrBlock:
        Description: Cidr block
        Type: String
        Default: 192.168.0.0/20

Resources: 
#vpc
      AccepterVPC:
          Type: AWS::EC2::VPC
          Properties:
            CidrBlock: !Ref VpcAccepterCidrBlock
            InstanceTenancy: default
            Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"
#vpc endpoint
      VpcEndpointToS3:
          Type: AWS::EC2::VPCEndpoint
          Properties: 
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Effect: Allow
                    Principal: '*'
                    Action:
                      - 's3:*'
                    Resource:
                    - "arn:aws:s3:::stelligent-u-desire.bbb/*"
                    - "arn:aws:s3:::stelligent-u-desire.bbb"
            ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
            RouteTableIds: 
            - !Ref AccepterRouteTable
            VpcEndpointType: Gateway
            VpcId: !Ref AccepterVPC

#private subnet
      DPrivateSubnet:
          Type: AWS::EC2::Subnet
          Properties:
            AvailabilityZone: "us-west-1a"
            VpcId: !Ref AccepterVPC
            CidrBlock: 192.168.0.0/24
            Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"

#route table
      AccepterRouteTable:
          Type: AWS::EC2::RouteTable
          Properties: 
            Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"
            VpcId: !Ref AccepterVPC
      
#subnet route table association(private subnet)
      DesiPrivateSbnRtTbAssoc:
          Type: AWS::EC2::SubnetRouteTableAssociation
          Properties: 
             RouteTableId: !Ref AccepterRouteTable
             SubnetId: !Ref DPrivateSubnet
#routes
      AccepterVpcRoute:
          Type: AWS::EC2::Route
          Properties: 
            RouteTableId: !Ref AccepterRouteTable
            VpcPeeringConnectionId: pcx-0d61a7315db4d6100
            DestinationCidrBlock: 10.16.0.0/16
         
     
#NACl
      AccepterPrivateNacl:
          Type: AWS::EC2::NetworkAcl
          Properties: 
            Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"
            VpcId: !Ref AccepterVPC
   #nacl entries rules
      TrafficFromRequesterVpcInbound:
          Type: AWS::EC2::NetworkAclEntry
          Properties: 
            CidrBlock: 10.16.0.0/16
            NetworkAclId: !Ref AccepterPrivateNacl
            Protocol: -1
            RuleAction: allow
            RuleNumber: 100
      TrafficFromS3Inbound:
          Type: AWS::EC2::NetworkAclEntry
          Properties: 
            CidrBlock: 54.231.0.0/17
            NetworkAclId: !Ref AccepterPrivateNacl
            Protocol: -1
            RuleAction: allow
            RuleNumber: 200    
      TrafficToRequesterVpcOutbound:
          Type: AWS::EC2::NetworkAclEntry
          Properties: 
            CidrBlock: 10.16.0.0/16
            NetworkAclId: !Ref AccepterPrivateNacl
            Egress: true
            Protocol: -1
            RuleAction: allow
            RuleNumber: 100
      TrafficToS3Outbound:
          Type: AWS::EC2::NetworkAclEntry
          Properties: 
            CidrBlock: 54.231.0.0/17
            NetworkAclId: !Ref AccepterPrivateNacl
            Egress: true
            Protocol: -1
            RuleAction: allow
            RuleNumber: 200
        
                
Outputs:
      VPCid:
        Description: the VPC id 
        Value: !Ref AccepterVPC
      PrivateSubnetid:
        Description: private subnet id
        Value: !Ref DPrivateSubnet
      VpcEndpointId:
        Description: Id of VpcEndpoint
        Value: !Ref VpcEndpointToS3