AWSTemplateFormatVersion: 2010-09-09
Description: "Create s3 bucket with sse-s3 encryption"
Resources: 
   MyBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: stelligent-u-desire.bb
       BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: true
  
   MyBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref MyBucket
        PolicyDocument:
          Statement:
          - Action: 
            - "s3:GetObject"
            Effect: Allow  
            Resource: "arn:aws:s3:::stelligent-u-desire.bb/*"
            Principal: "*"
  
   ReadAllS3Buckets:
     Type: AWS::IAM::ManagedPolicy
     Properties:
       ManagedPolicyName: reads3bucket
       PolicyDocument: 
          Version: 2012-10-17
          Statement:
          - Sid: AllowListingReading
            Effect: Allow
            Action: "s3:*"
            Resource: 
            - "arn:aws:s3:::stelligent-u-desire.bahbioh"
            - "arn:aws:s3:::stelligent-u-desire.bahbioh/*"
       Users:
        - "desire.bahbioh.labs"