AWSTemplateFormatVersion: 2010-09-09
Description: "create a new user and a policy that manages that user"

Parameters:
  NewUserName:
    Type: String
    Default: cfnuser2
  ImportedStackName:
    Type: String
    Default: desirebahbioh-export-mystack-

Resources:
   NewIamUser:
     Type: AWS::IAM::User
     Properties:
       UserName: !Ref NewUserName
       LoginProfile:
          Password: myP@ssword2!
       ManagedPolicyArns:
       - Fn::ImportValue:
           !Sub "${ImportedStackName}-ManagedPolicyARN"