AWSTemplateFormatVersion: 2010-09-09

Description: launching test instance

Parameters:
    AMI:
      Type: AWS::EC2::Image::Id
    InstanceType:
      Type: String
    KeyPair:
      Type: AWS::EC2::KeyPair::KeyName
Resources:
#public EC2 for VPC
    DesiEc2:
        Type: AWS::EC2::Instance
        Properties: 
          AvailabilityZone: "us-east-1a"
          SubnetId: subnet-051cac299ed6df556
          ImageId: !Ref AMI
          InstanceType: !Ref InstanceType
          KeyName: !Ref KeyPair
          Tenancy: default
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.7"
          SecurityGroupIds:
          - !Ref DesiSecurityGroups
#private EC2 for VPC
    DesiPrivateEc2:
        Type: AWS::EC2::Instance
        Properties: 
          AvailabilityZone: "us-east-1a"
          SubnetId: subnet-0538c9469f8da0147
          ImageId: !Ref AMI
          InstanceType: !Ref InstanceType
          KeyName: !Ref KeyPair
          Tenancy: default
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.7"
          SecurityGroupIds:
          - !Ref DesiSecurityGroups
    DesiSecurityGroups:
        Type: AWS::EC2::SecurityGroup
        Properties: 
          GroupDescription: Allow ICMP and ssh
          GroupName: sshping
          SecurityGroupIngress: 
          - IpProtocol: icmp
            FromPort: -1
            ToPort: -1
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.7"
          VpcId: vpc-00aeadafe7662a446
    DesiEIP:
        Type: AWS::EC2::EIP
        Properties: 
          Domain: vpc
          InstanceId: !Ref DesiEc2
          Tags: 
          - Key: user
            Value: desire.bahbioh.labs
          - Key: stelligent-u-lesson
            Value: "4.1"
          - Key: stelligent-u-lab
            Value: "4.1.7"

Outputs:
  PublicInstanceId:
    Description: Public Ec2 instance ID
    Value: !Ref DesiEc2
  PublicInstancePrivateIP:
    Description: Public instance's Private IP
    Value: !GetAtt DesiEc2.PrivateIp
  ElasticPublicIP:
    Description: Public instance's Public IP
    Value: !Ref DesiEIP
  PrivateInstanceIP:
    Description: Private instance's Private IP
    Value: !GetAtt DesiPrivateEc2.PrivateIp