AWSTemplateFormatVersion: 2010-09-09

Description: launching test instance

Parameters:
    AMI:
      Type: AWS::EC2::Image::Id
    InstanceType:
      Type: String
    KeyPair:
      Type: AWS::EC2::KeyPair::KeyName
Resources:
    DesiEc2:
        Type: AWS::EC2::Instance
        Properties: 
          AvailabilityZone: "us-east-1a"
          SubnetId: subnet-029c11386479ecb5e
          ImageId: !Ref AMI
          InstanceType: !Ref InstanceType
          KeyName: !Ref KeyPair
          Tenancy: default
          PrivateIpAddress: 10.16.0.5
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.7"
          SecurityGroupIds:
          - !Ref DesiSecurityGroups
    DesiPrivateEc2:
        Type: AWS::EC2::Instance
        Properties: 
          AvailabilityZone: "us-east-1a"
          SubnetId: subnet-0dacf183c234f12e7
          ImageId: !Ref AMI
          InstanceType: !Ref InstanceType
          KeyName: !Ref KeyPair
          Tenancy: default
          PrivateIpAddress: 10.16.1.5
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.7"
          SecurityGroupIds:
          - !Ref DesiSecurityGroups
    DesiSecurityGroups:
        Type: AWS::EC2::SecurityGroup
        Properties: 
          GroupDescription: Allow ICMP and ssh
          GroupName: sshping
          SecurityGroupIngress: 
          - IpProtocol: icmp
            FromPort: -1
            ToPort: -1
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.7"
          VpcId: vpc-06c2f8ae988ac0734
    DesiEIP:
        Type: AWS::EC2::EIP
        Properties: 
          Domain: vpc
          InstanceId: !Ref DesiEc2
          Tags: 
          - Key: user
            Value: desire.bahbioh.labs
          - Key: stelligent-u-lesson
            Value: "4.1"
          - Key: stelligent-u-lab
            Value: "4.1.7"

Outputs:
  InstanceId:
    Description: Ec2 instance ID
    Value: !Ref DesiEc2
  PrivateIP:
    Description: private ip address
    Value: !GetAtt DesiEc2.PrivateIp
  ElasticPublicIP:
    Description: public ip address
    Value: !Ref DesiEIP