AWSTemplateFormatVersion: 2010-09-09
Description: custom vpc 

Parameters: 
     VpcCidrBlock:
        Description: Cidr block
        Type: String

Resources: 
   DesireVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: !Ref VpcCidrBlock
        InstanceTenancy: default
   DSubnet01:
        Type: AWS::EC2::Subnet
        Properties:
          AvailabilityZone: "us-east-1a"
          VpcId: !Ref DesireVPC
          CidrBlock: 10.16.0.0/24
          Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.1"
Outputs:
   VPCid:
     Description: the VPC id 
     Value: !Ref DesireVPC
   Subnetid:
     Description: the subnet id
     Value: !Ref DSubnet01