AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role with read-only access to all IAM resources

Resources: 
   IAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: iam-role
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal:
              Service: 
              - "iam.amazonaws.com"
            Action: "sts:AssumeRole"
   S3Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: s3-role
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal:
              Service: 
              - "s3.amazonaws.com"
            Action: "sts:AssumeRole"
   ReadOnlyPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: iam-read-only
        Description: Policy for re-use allowing read-only access on IAM and S3 resources
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: 
            - "iam:Get*"
            - "s3:Get*"
            Resource: "*"
        Roles:
        - !Ref IAMRole
        - !Ref S3Role