AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role with read-only access to all IAM resources

Resources: 
   ReadOnlyRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: iam-read-only
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal:
              Service: 
                - "iam.amazonaws.com"
            Action: "sts:AssumeRole"
        Policies:
        - PolicyName: ReadOnlyResources
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "iam:Get*"
                Resource: "*"
