AWSTemplateFormatVersion: '2010-09-09'
Resources:
#auto scaling group
  WebServerAsg:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AutoScalingGroupName: 'AutomationBoxes'
      VPCZoneIdentifier:
        - subnet-0ddf1015d31bb8469 # Find public subnets within the default VPC or 
        - subnet-0e57092e5f64abb1c
      DesiredCapacity: '3'
      HealthCheckType: 'ELB'
      HealthCheckGracePeriod: 30 
      LaunchConfigurationName: !Ref WebServersLC
      MaxSize: '3'
      MinSize: '3'
      TargetGroupARNs: 
      - !Ref MyApplicationLoadBalancerTargetGrp 
#load balancer target group 
  MyApplicationLoadBalancerTargetGrp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 20
      HealthCheckPath: /BADindex.html
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 6
      HealthyThresholdCount: 3
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: "20"
      Name: MyalbTargetGroup
      Port: 80
      Protocol: HTTP
      Tags: 
        - Key: user
          Value: desire.bahbioh.labs
        - Key: stelligent-u-lesson
          Value: "7.1"
        - Key: stelligent-u-lab
          Value: "7.1.1"
      TargetType: instance
      UnhealthyThresholdCount: 2
      VpcId: vpc-0c81659bfa7cdf898
#application load balancer
  MyAppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups: 
        - sg-0a269819d700c9119
      Subnets: 
        - subnet-0ddf1015d31bb8469 # Find public subnets within the default VPC or 
        - subnet-0e57092e5f64abb1c
      Tags: 
        - Key: user
          Value: desire.bahbioh.labs
        - Key: stelligent-u-lesson
          Value: "7.1"
        - Key: stelligent-u-lab
          Value: "7.1.1"
      Type: application
#load balancing listener
  MyAlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
      - TargetGroupArn: !Ref MyApplicationLoadBalancerTargetGrp
        Type: forward
      LoadBalancerArn: !Ref MyAppLoadBalancer
      Port: 80
      Protocol: HTTP
#auto scaling launch config
  WebServersLC:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      ImageId: ami-0000025f7c02a13b2
      InstanceType: t2.micro
      LaunchConfigurationName: SimpleWebServerLC
      SecurityGroups:
        - sg-0a269819d700c9119
      UserData: 
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xe

            yum install -y aws-cfn-bootstrap

            # Install the files and packages from the metadata
            /opt/aws/bin/cfn-init -v \
              --stack ${AWS::StackName} \
              --resource WebServersLC \
              --configsets All \
              --region ${AWS::Region}

            # Signal the status from cfn-init
            /opt/aws/bin/cfn-signal -e $? \
              --stack ${AWS::StackName} \
              --resource WebServersLC \
              --region ${AWS::Region}
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          All:
            - ConfigureStelligentProject
        ConfigureStelligentProject:
          packages:
            yum:
              nginx: []
          files:
            /usr/share/nginx/html/index.html:
              content: '<p>Automation for the People</p>'
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              nginx:
                enabled: 'true'
                ensureRunning: 'true'

Outputs:
  LoadBalancerDNSName:
     Description: load balancer DNS endpoint
     Value: !GetAtt MyAppLoadBalancer.DNSName

