AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role with read-only access to all IAM resources

Parameters:
    IAMroleManagedPolicyArn:
        Description: IAM role managed policy
        Type: String
    EC2RoleManagedPolicyArn1:
        Description: EC2 role managed policy
        Type: String
    EC2RoleManagedPolicyArn2:
        Description: EC2 role managed policy
        Type: String

Resources: 
   IAMRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: iam-role
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal:
              Service: 
              - "iam.amazonaws.com"
            Action: "sts:AssumeRole"
        ManagedPolicyArns: 
        - !Ref IAMroleManagedPolicyArn
   EC2Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ec2-role
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal:
              Service: 
              - "ec2.amazonaws.com"
              - "iam.amazonaws.com"
            Action: "sts:AssumeRole"
        ManagedPolicyArns: 
        - !Ref EC2RoleManagedPolicyArn1
        - !Ref EC2RoleManagedPolicyArn2

Outputs:
  IAMroleMngPolicyArn:
     Description: IAM role Arn of managed policies
     Value: !Ref IAMroleManagedPolicyArn 
  EC2roleMngPolicyArn1:
     Description: EC2 role Arn of managed policies
     Value: !Ref EC2RoleManagedPolicyArn1
  EC2roleMngPolicyArn2:
     Description: EC2 role Arn of managed policies
     Value: !Ref EC2RoleManagedPolicyArn2
     