AWSTemplateFormatVersion: 2010-09-09

Description: launching test instance

Parameters:
    AMI:
      Type: AWS::EC2::Image::Id
    InstanceType:
      Type: String
    KeyPair:
      Type: AWS::EC2::KeyPair::KeyName
Resources:
    DesiEc2:
        Type: AWS::EC2::Instance
        Properties: 
          AvailabilityZone: "us-east-1a"
          SubnetId: subnet-083f0cedf7e729189
          ImageId: !Ref AMI
          InstanceType: !Ref InstanceType
          KeyName: !Ref KeyPair
          Tenancy: default
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"
          SecurityGroupIds:
          - !Ref DesiSecurityGroups
    DesiPrivateEc2:
        Type: AWS::EC2::Instance
        Properties: 
          AvailabilityZone: "us-east-1a"
          SubnetId: subnet-091a8dca3fbaf6a78
          ImageId: !Ref AMI
          InstanceType: !Ref InstanceType
          KeyName: !Ref KeyPair
          Tenancy: default
          #PrivateIpAddress: 10.16.1.5
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"
          SecurityGroupIds:
          - !Ref DesiSecurityGroups
    DesiSecurityGroups:
        Type: AWS::EC2::SecurityGroup
        Properties: 
          GroupDescription: Allow ICMP and ssh
          GroupName: sshping
          SecurityGroupIngress: 
          - IpProtocol: icmp
            FromPort: -1
            ToPort: -1
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.8"
          VpcId: vpc-03d7fee22349df54a
    DesiEIP:
        Type: AWS::EC2::EIP
        Properties: 
          Domain: vpc
          InstanceId: !Ref DesiEc2
          Tags: 
          - Key: user
            Value: desire.bahbioh.labs
          - Key: stelligent-u-lesson
            Value: "4.1"
          - Key: stelligent-u-lab
            Value: "4.1.8"
Outputs:
  PublicInstanceId:
    Description: Ec2 instance ID
    Value: !Ref DesiEc2
  PublicInstancePrivateIP:
    Description: private ip address
    Value: !GetAtt DesiEc2.PrivateIp
  PublicInstanceElasticIP:
    Description: public ip address
    Value: !Ref DesiEIP
  PrivateInstancePrivateIP:
    Description: private instance ip address
    Value: !GetAtt DesiPrivateEc2.PrivateIp
