#Query the AWS-maintained AMIs via SSM parameters
#aws ssm get-parameters-by-path --path /aws/service/ami-windows-latest | jq ".Parameters[].Name" | grep "English" | grep "\-2019"
#or

#choose the appropriate AMI path and include in CFN parameters
AWSTemplateFormatVersion: 2010-09-09

Description: Launch EC2 instance through launch template

Parameters:
   UbuntuLatestAMI:
     Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
     Default: /aws/service/canonical/ubuntu/server/18.04/stable/current/amd64/hvm/ebs-gp2/ami-id
Resources:
   MyEc2Ubuntu:
     Type: AWS::EC2::Instance           
     Properties:
        ImageId: !Ref UbuntuLatestAMI
        InstanceType: t2.micro
        KeyName: dbb  
        UserData:
            Fn::Base64: !Sub |
              #!/bin/bash -xe
              sudo mkfs -t ext4 /dev/xvdh
              sudo mkdir /data
              sudo echo "/dev/xvdh       /data   ext4    defaults,nofail 0       2" >> /etc/fstab
              sudo mount -a
              sudo echo "hello world" > /data/hello.txt
              
        SecurityGroupIds:
        - !Ref MySecurityGroupdbb
   MyEBSVolume:
      Type: AWS::EC2::Volume
      Properties: 
        AvailabilityZone: !GetAtt MyEc2Ubuntu.AvailabilityZone
        Size: 3
        Tags: 
        - Key: user
          Value: desire.bahbioh.labs
        - Key: stelligent-u-lesson
          Value: "5.3"
        - Key: stelligent-u-lab
          Value: "5.3.2"
        VolumeType: gp2
   MyElacticIPdbb:
      Type: AWS::EC2::EIP
      Properties: 
        Domain: vpc
        InstanceId: !Ref MyEc2Ubuntu
        Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "5.2"
            - Key: stelligent-u-lab
              Value: "5.2.1"
   MySecurityGroupdbb:
      Type: AWS::EC2::SecurityGroup
      Properties: 
        GroupDescription: Allow ICMP trafic
        SecurityGroupIngress: 
        - Description: Allow all traffic from ICMP from everywhere
          CidrIp: 0.0.0.0/0
          IpProtocol: icmp
          FromPort: -1
          ToPort: -1
        - Description: Allow SSH trafic from everywhere
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        Tags: 
        - Key: user
          Value: desire.bahbioh.labs
        - Key: stelligent-u-lesson
          Value: "5.3"
        - Key: stelligent-u-lab
          Value: "5.3.2"
   Ec2VolumeAttachement:
      Type: AWS::EC2::VolumeAttachment
      Properties: 
        Device: /dev/xvdh
        InstanceId: !Ref MyEc2Ubuntu
        VolumeId: !Ref MyEBSVolume

Outputs:
  UbuntuElasticIP:
     Description: Elastic Ip of ubuntu instance
     Value: !Ref MyElacticIPdbb
  UbuntuInstanceId:
     Description: Ubuntu instance Id
     Value: !Ref MyEc2Ubuntu
      