AWSTemplateFormatVersion: 2010-09-09

Description: Launch EC2 instance through launch template

Resources:
   MyLaunchTemplateDbb: 
      Type: AWS::EC2::LaunchTemplate
      Properties: 
        LaunchTemplateData: 
          InstanceType: t2.micro
          KeyName: dezKey
          SecurityGroupIds: 
          - sg-04451ea6d4982b110
          TagSpecifications: 
          - ResourceType: instance
            Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "5.1.1"
        LaunchTemplateName: Stelligent-u-dbb
   MyEc2Windows:
     Type: AWS::EC2::Instance
     Properties:
        ImageId: ami-0088977e66ac3915d 
        LaunchTemplate:
          LaunchTemplateId: !Ref MyLaunchTemplateDbb
          Version: !GetAtt MyLaunchTemplateDbb.LatestVersionNumber
   MyEc2Ubuntu:
     Type: AWS::EC2::Instance
     Properties:
        ImageId: ami-0739f8cdb239fe9ae  
        LaunchTemplate:
          LaunchTemplateId: !Ref MyLaunchTemplateDbb
          Version: !GetAtt MyLaunchTemplateDbb.LatestVersionNumber
