AWSTemplateFormatVersion: 2010-09-09

Description: EC2 instance launch template for ASG

Resources:
#launch template
   MyLaunchTemplateDbb: 
      Type: AWS::EC2::LaunchTemplate
      Properties: 
        LaunchTemplateData: 
          ImageId: ami-007a4d852ac16f59e
          InstanceType: c5.large
          KeyName: dbb
          TagSpecifications: 
          - ResourceType: instance
            Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "6.3"
            - Key: stelligent-u-lab
              Value: "6.3.1"
          SecurityGroupIds:
          - !GetAtt MySecurityGroupdbb.GroupId 
#auto scaling group
   MyAutoScalingGroupdbb:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties: 
          AvailabilityZones:
          - us-east-1a
          DesiredCapacity: "1"
          HealthCheckType: EC2
          Cooldown: "60"
          LaunchTemplate:
            LaunchTemplateId: !Ref MyLaunchTemplateDbb
            Version: !GetAtt MyLaunchTemplateDbb.LatestVersionNumber
          MaxSize: "3"
          MinSize: "1"
          Tags: 
          - Key: user
            Value: desire.bahbioh.labs
            PropagateAtLaunch: true
          - Key: stelligent-u-lesson
            Value: "6.3"
            PropagateAtLaunch: true
          - Key: stelligent-u-lab
            Value: "6.3.1"
            PropagateAtLaunch: true
          VPCZoneIdentifier:
          - subnet-0ddf1015d31bb8469
        UpdatePolicy:
           AutoScalingReplacingUpdate:
              WillReplace: true
#cloudwatch alarms
   MyCloudWatchAlarmDbb:
          Type: AWS::CloudWatch::Alarm
          Properties: 
            AlarmActions: 
            - !Ref MyAutoScalingPolicy
            AlarmDescription: scale when CPU > 60% over a period of 2min
            ComparisonOperator: GreaterThanThreshold
            EvaluationPeriods: 2
            MetricName: CPUUtilization
            Threshold: 60
            Namespace: AWS/EC2
            Period: 60
            Statistic: Average
            Dimensions:
            - Name: "Myasgrule"
              Value: !Ref MyAutoScalingGroupdbb
   MyCloudWatchAlarmScaleIn:
          Type: AWS::CloudWatch::Alarm
          Properties: 
            AlarmActions: 
            - !Ref MyAutoScalingPolicy
            AlarmDescription: scale in when CPU < 40% over a period of 2min
            ComparisonOperator: LessThanThreshold
            EvaluationPeriods: 2
            MetricName: CPUUtilization
            Threshold: 60
            Namespace: AWS/EC2
            Period: 60
            Statistic: Average
            Dimensions:
            - Name: "Myasgrule"
              Value: !Ref MyAutoScalingGroupdbb
#auto scaling policy
   MyAutoScalingPolicy:
          Type: AWS::AutoScaling::ScalingPolicy
          Properties: 
            AdjustmentType: ChangeInCapacity
            AutoScalingGroupName: !Ref MyAutoScalingGroupdbb
            PolicyType: SimpleScaling
            ScalingAdjustment: 1
#security group
   MySecurityGroupdbb:
      Type: AWS::EC2::SecurityGroup
      Properties: 
        GroupDescription: Allow ssh trafic
        SecurityGroupIngress: 
        - Description: Allow SSH trafic from everywhere
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        Tags: 
        - Key: user
          Value: desire.bahbioh.labs
        - Key: stelligent-u-lesson
          Value: "6.3"
        - Key: stelligent-u-lab
          Value: "6.3.1"

