AWSTemplateFormatVersion: 2010-09-09
Description: custom vpc 

Parameters: 
     VpcCidrBlock:
        Description: Cidr block
        Type: String

Resources: 
#vpc
      DesireVPC:
          Type: AWS::EC2::VPC
          Properties:
            CidrBlock: !Ref VpcCidrBlock
            InstanceTenancy: default
            Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.2"
#subnet
      DSubnet01:
          Type: AWS::EC2::Subnet
          Properties:
            AvailabilityZone: "us-east-1a"
            VpcId: !Ref DesireVPC
            CidrBlock: 10.16.0.0/24
            Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.2"
#internet Gateway
      DesiIGW:
          Type: AWS::EC2::InternetGateway
          Properties:
            Tags:
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.2"
#internet gateway attachement
      DesiIgwAttachement:
          Type: AWS::EC2::VPCGatewayAttachment
          Properties: 
            InternetGatewayId: !Ref DesiIGW
            VpcId: !Ref DesireVPC
#route table
      DesiRouteTable:
          Type: AWS::EC2::RouteTable
          Properties: 
            Tags: 
            - Key: user
              Value: desire.bahbioh.labs
            - Key: stelligent-u-lesson
              Value: "4.1"
            - Key: stelligent-u-lab
              Value: "4.1.2"
            VpcId: !Ref DesireVPC
#subnet route table association
      DesiSbnRtTbAssoc:
          Type: AWS::EC2::SubnetRouteTableAssociation
          Properties: 
             RouteTableId: !Ref DesiRouteTable
             SubnetId: !Ref DSubnet01
#routes
      DesiRoute:
          Type: AWS::EC2::Route
          Properties:
            GatewayId: !Ref DesiIGW
            RouteTableId: !Ref DesiRouteTable
            DestinationCidrBlock: 0.0.0.0/0

Outputs:
      VPCid:
        Description: the VPC id 
        Value: !Ref DesireVPC
      Subnetid:
        Description: the subnet id
        Value: !Ref DSubnet01