AWSTemplateFormatVersion: 2010-09-09

Description: sample S3 bucket

Resources:
   MySampleBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: stelligent-u-dbb-cwlogs-sample 
        Tags: 
          - Key: user
            Value: desire.bahbioh.labs
          - Key: stelligent-u-lesson
            Value: "8.2"
          - Key: stelligent-u-lab
            Value: "8.2.2"