AWSTemplateFormatVersion: 2010-09-09
Description: User assuming a Role
Resources:
   MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: unrestricted.desirebb
   S3role:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Principal: 
              AWS: arn:aws:iam::324320755747:user/desire.bahbioh.labs
            Action: "sts:AssumeRole"
        Policies:
          - PolicyDocument:
              Version: 2012-10-17
              Statement:
              - Effect: Allow
                Action: 's3:List*'
                Resource: arn:aws:s3:::unrestricted.desirebb
                Condition:
                  StringEquals:
                    s3:prefix: lebowski
            PolicyName: s3prefixpol
        RoleName: iam-s3-prefix
Outputs:
  RoleArn:
     Description: Arn of s3fullaccess
     Value: !GetAtt S3role.Arn